# Generated by Django 2.2.1 on 2019-05-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('num', models.IntegerField(default=1, verbose_name='人数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.User')),
            ],
            options={
                'verbose_name': '预定',
                'verbose_name_plural': '预定',
            },
        ),
    ]
