# Generated by Django 2.2.1 on 2019-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='num',
            field=models.PositiveIntegerField(default=1, verbose_name='人数'),
        ),
    ]
