# Generated by Django 2.2.1 on 2019-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190530_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='num',
            field=models.PositiveIntegerField(verbose_name='人数'),
        ),
    ]
