# Generated by Django 2.2.1 on 2019-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20190530_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='num',
            field=models.CharField(max_length=30, verbose_name='人数'),
        ),
    ]
